In [1]:
from theano import tensor as T
import lasagne_dev as nn
import numpy as np
import pickle
from input_process import read_images
import random
import math
import cmath
from g_gradient import *
import timeit
import unet
from collections import OrderedDict

/usr/local/lib/python2.7/dist-packages/theano/gpuarray/dnn.py:135: UserWarning: Your cuDNN version is more recent than Theano. If you encounter problems, try updating Theano or downgrading cuDNN to version 5.1.
  warnings.warn("Your cuDNN version is more recent than "
Using cuDNN version 6020 on context None
Mapped name None to device cuda: Quadro K2000 (0000:01:00.0)


In [2]:
start = timeit.default_timer()
epoch = 1
shape = [5,1,116,116]

input_var = T.tensor4('input_var')  
label_var = T.tensor4('label_var')

[network, loss, test_loss, test_acc, output_det] = unet.network(input_var, label_var, shape)


params = nn.layers.get_all_params(network)
lr = theano.shared(nn.utils.floatX(1e-4)) # learning rate
updates = nn.updates.adam(loss,params, learning_rate=lr) # adam most widely used update scheme

gs = nn.layers.get_all_gs(network)

gs_updates = g_updates(loss, params, gs)
updates = OrderedDict()
updates_old = nn.updates.adam(loss, params, learning_rate=lr)

stop = timeit.default_timer()
print(stop-start)

0.199249982834


In [79]:
size = 5
bond = math.floor(size/2)

gg_shared = theano.shared(np.array([1,2,3,4,5],dtype=np.float32))
g_params = [gg_shared[0],gg_shared[1],gg_shared[2],gg_shared[3],gg_shared[4]]
f,gamma,sigma,theta,psi = g_params
x_range = np.linspace(-bond, bond, size)
y_range = np.linspace(-bond, bond, size)

xt,yt = np.meshgrid(x_range,y_range)
xt = xt.astype(np.float32)
yt = yt.astype(np.float32)
a = gabor_filter_tensor_dev(xt,yt,g_params)
Ws = theano.tensor.stack([a,a,a,a])
Ws.reshape([4,1,5,5])
Ws.shape.eval()

array([4, 5, 5])

In [27]:
start = timeit.default_timer()
gabor_weight_update_dev(shape, gs[0])
stop = timeit.default_timer()
print(stop-start)

0.0554769039154


In [ ]:
start = timeit.default_timer()
## generate updates for params

for i in range (0,len(gs)):

    gs_new = gs_updates[gs[i]]
    ws = params[i*2]
    [num_filters, num_channels, filter_size, filter_size] = ws.get_value().shape
    W = gabor_weight_update_dev([num_filters, num_channels, filter_size, filter_size], gs_new)
    #updates[ws] = theano.shared(W)
    updates[ws] = W
    updates[params[i*2+1]] = updates_old[params[i*2+1]]

stop = timeit.default_timer()
print(stop-start)

In [111]:
x = gs[1]
gs_updates[gs[1]].broadcastable
#x.broadcastable

(False, False, False)

In [112]:
from input_process import read_images
from train import run_params
import pickle
import numpy as np
import random

size = (116, 116) # resize images

pkl_file = open('../fnames_collection_2', 'r')
fnames = pkl_file.readline()
fnames = fnames.split(' ')
for i in range (0,len(fnames)):
	fnames[i] = str(fnames[i])
	fnames[i] = 'image' + fnames[i] + '.png'

'''
index = fnames[1:4000]
random.shuffle(index)
train_index = index[0:4000]
test_index = fnames[4000:4200]
'''
train_index = fnames[0:5]
test_index = fnames[10:15]



label_path = '../NewPNGlabeled/'
ori_path = '../JpegOriginalImg/'

train_input, train_label = read_images(label_path, ori_path, train_index, size)
test_input, test_label = read_images(label_path, ori_path, test_index, size)

In [115]:
epoch = 1
shape = [5,1,116,116]


input_var = train_input
label_var = train_label

[network, loss, test_loss, test_acc, output_det] = unet.network(input_var, label_var, shape)


params = nn.layers.get_all_params(network)
lr = theano.shared(nn.utils.floatX(1e-4)) # learning rate
updates = nn.updates.adam(loss,params, learning_rate=lr) # adam most widely used update scheme

gs = nn.layers.get_all_gs(network)

gs_updates = g_updates(loss, params, gs)
updates = OrderedDict()
updates_old = nn.updates.adam(loss, params, learning_rate=lr)


[network, loss, test_loss, test_acc, output_det] = unet.network(input_var, label_var, shape)


params = nn.layers.get_all_params(network)
lr = theano.shared(nn.utils.floatX(1e-4)) # learning rate
updates = nn.updates.adam(loss,params, learning_rate=lr) # adam most widely used update scheme

gs = nn.layers.get_all_gs(network)

gs_updates = g_updates(loss, params, gs)
updates = OrderedDict()
updates_old = nn.updates.adam(loss, params, learning_rate=lr)


In [127]:
print(len(gs))
print(gs[1].shape.eval())
gs_updates[gs[1]].shape.eval()

2
[ 1 64  5]


array([64, 64,  5])

In [173]:
gs_gradients = []
gradients = nn.updates.get_or_compute_grads(loss, params)

w_index = 1
# First Loop
# print(w_index)

ws = params[w_index*2]
g_params = gs[w_index].get_value()
ws_gradients = gradients[w_index*2]

[num_filters, num_channels, filter_size, filter_size] = ws.get_value().shape

position = int(math.floor(filter_size/2))
ws_grad = ws_gradients[:,:,position:position+1,position]

# Second and third Loop
additions = []
for i in range (0, num_filters):
    for j in range (0, num_channels):
        g = g_params[i,j,:]
        additions.append(g_psi(0,0,g))

additions =  np.array(additions,dtype=np.float32).reshape(num_filters,num_channels,-1)
g_gradients = theano.tensor.concatenate([ws_grad*0, ws_grad*0, ws_grad*0, ws_grad*0, ws_grad], axis=2)*additions
gs_gradients.append(g_gradients)
gs_updates = nn.updates.adam_dev(gs_gradients, gs)

In [155]:
g_gradients = theano.tensor.concatenate([ws_grad, ws_grad, ws_grad, ws_grad, ws_grad], axis=2)*additions

Elemwise{mul,no_inplace}.0

In [174]:
7

[ 1 64  5]
(1, 64, 1)


In [175]:
print(theano.tensor.concatenate([ws_grad, ws_grad, ws_grad, ws_grad, ws_grad], axis=2).eval())
print(additions)

[[[  7.22231835e-06   7.22231835e-06   7.22231835e-06   7.22231835e-06
     7.22231835e-06]
  [  2.49578043e-05   2.49578043e-05   2.49578043e-05   2.49578043e-05
     2.49578043e-05]
  [  2.33826268e-06   2.33826268e-06   2.33826268e-06   2.33826268e-06
     2.33826268e-06]
  [  9.81006542e-06   9.81006542e-06   9.81006542e-06   9.81006542e-06
     9.81006542e-06]
  [  1.07507985e-04   1.07507985e-04   1.07507985e-04   1.07507985e-04
     1.07507985e-04]
  [  1.87808405e-06   1.87808405e-06   1.87808405e-06   1.87808405e-06
     1.87808405e-06]
  [  2.55415234e-05   2.55415234e-05   2.55415234e-05   2.55415234e-05
     2.55415234e-05]
  [  3.26521040e-05   3.26521040e-05   3.26521040e-05   3.26521040e-05
     3.26521040e-05]
  [  7.31088858e-06   7.31088858e-06   7.31088858e-06   7.31088858e-06
     7.31088858e-06]
  [  1.49044830e-08   1.49044830e-08   1.49044830e-08   1.49044830e-08
     1.49044830e-08]
  [  3.99758648e-07   3.99758648e-07   3.99758648e-07   3.99758648e-07
     3.99

In [176]:
print(gs_gradients[0].eval())

[[[  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
     6.16273655e-06]
  [ -0.00000000e+00  -0.00000000e+00  -0.00000000e+00  -0.00000000e+00
    -1.69808536e-05]
  [ -0.00000000e+00  -0.00000000e+00  -0.00000000e+00  -0.00000000e+00
    -1.75806110e-06]
  [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
     3.90245361e-07]
  [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
     8.30260455e-04]
  [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
     6.46541639e-06]
  [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
     1.76668236e-05]
  [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
     3.14475237e-08]
  [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
     5.86701890e-06]
  [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
     3.82451804e-09]
  [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
     5.55

In [ ]:
from collections import OrderedDict
updates = OrderedDict()
updates_old = nn.updates.adam(loss, params, learning_rate=lr)
for i in range (0,len(gs)):
    print(i)
    gs_new = gs_updates[gs[0]]
    ws = params[i*2]
    [num_filters, num_channels, filter_size, filter_size] = ws.get_value().shape
    W = gabor_weight_update([num_filters, num_channels, filter_size, filter_size], gs_new)
    #updates[ws] = theano.shared(W)
    updates[ws] = W
    updates[params[i*2+1]] = updates_old[params[i*2+1]]


In [ ]:
gradients = nn.updates.get_or_compute_grads(loss, params)
ws_gradients = gradients[0]
ws_gradients[0,0,1,1]
theano.shared(ws_gradients)

In [45]:
def gabor_filter_dev2(x,y,params):
    f,gamma,sigma,theta,psi = params
    xt = x*theano.tensor.cos(theta) + y*theano.tensor.sin(theta)
    yt = -x*theano.tensor.sin(theta) + y*theano.tensor.cos(theta)
    z1 = -(xt**2 + (gamma*yt)**2)/(2*sigma**2)
    z2 = 2*math.pi*f*xt+psi
    #z2 = 1j*2*math.pi*f*xt+psi
    value = f**2/(math.pi*gamma)*theano.tensor.exp(z1)*theano.tensor.cos(z2)
    return value

def gabor_filter_1(x,y,params):
    f,gamma,sigma,theta,psi = params
    xt = x*math.cos(theta) + y*math.sin(theta)
    yt = -x*math.sin(theta) + y*math.cos(theta)
    z1 = -(xt**2 + (gamma*yt)**2)/(2*sigma**2)
    z2 = 1j*2*math.pi*f*xt+psi*1j
    value = f**2/(math.pi*gamma)*math.exp(z1)*cmath.exp(z2)
    return value

def gabor_filter_2(x,y,params):
    f,gamma,sigma,theta,psi = params
    xt = x*math.cos(theta) + y*math.sin(theta)
    yt = -x*math.sin(theta) + y*math.cos(theta)
    z1 = -(xt**2 + (gamma*yt)**2)/(2*sigma**2)
    z2 = 2*math.pi*f*xt+psi
    value = f**2/(math.pi*gamma)*math.exp(z1)*math.cos(z2)
    return value

In [ ]:
g_try = gs_updates[gs[0]]
updates
g_try.dtype

In [ ]:
gs_updates.keys()

In [ ]:
updates_old = nn.updates.adam(loss, params, learning_rate=lr)
updates_old[params[0]].dtype

In [ ]:
gvalue = gs[0].get_value()
g = gvalue[0,0,:]
g_psi(0,0,g)
